name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: wyvox/action@v1

      - name: Lint
        run: pnpm --filter "ember-cli-mirage" lint

      - name: Run Tests
        run: pnpm --filter "ember-cli-mirage" test:ember

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: wyvox/action@v1
        with:
          pnpm-args: "--fix-lockfile"

      - name: Run Tests
        run: pnpm test:ember
        working-directory: packages/ember-cli-mirage

  test-docs:
    name: "Docs"
    runs-on: ubuntu-latest

    steps:
      - uses: wyvox/action@v1
        with:
          pnpm-args: "--fix-lockfile"

      - name: Lint
        run: pnpm --filter "ember-cli-mirage-docs" lint

      - name: Run Tests
        run: pnpm --filter "ember-cli-mirage-docs" test:ember

  test-app-01:
    name: "Tests - Basic App"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: wyvox/action@v1

      - name: Lint
        run: pnpm --filter "basic-app" lint

      - name: Run Tests
        run: pnpm --filter "basic-app" test

  test-app-02:
    name: "Tests - App That Excludes Mirage"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: wyvox/action@v1

      - name: Lint
        run: pnpm --filter "app-that-excludes-mirage" lint

      - name: Run Tests
        run: pnpm --filter "app-that-excludes-mirage" test

  test-app-03:
    name: "Tests - Embroider"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: wyvox/action@v1

      - name: Lint
        run: pnpm --filter "embroider-app" lint

      - name: Run Tests
        run: pnpm --filter "embroider-app" test


  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: 'test'

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.12
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic

    steps:
      - uses: wyvox/action@v1

      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
        working-directory: packages/ember-cli-mirage
